name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  execute:
    timeout-minutes: 3
    runs-on:
      labels: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: compose up
        run: docker-compose up --build -d
